### ISSUE TITLE
Problema con rappresentazione OpenData

### ISSUE THREAD

**Issue by fausto-mancini-dtd** [teamdigitale/padigitale2026-opendata#32]
Buongiorno, segnalo che in relazione agli open data di PA2026, l'avviso 1.4.5, nelle candidature, viene rappresentato in maniera errata (**"1.4.5 "Piattaforma Notifiche Digitali” Comuni (Settembre 2022)**", rendendo di fatto il file inservibile per un parse automatico.

**Comment by radema** [comment]
ciao @fausto-mancini-dtd, dovrebbe essere modificata la stringa in maniera tale da evitare l'errore.

**Comment by fausto-mancini-dtd** [comment]
> ciao @fausto-mancini-dtd, dovrebbe essere modificata la stringa in maniera tale da evitare l'errore.

Esatto. Quando sarà modificata?

**Comment by radema** [comment]
Ciao, dovrebbe essere stata già modificata con l'ultimo aggiornamento della repository.
