### ISSUE TITLE
Riga 22 di avvisi.csv malformata

### ISSUE THREAD

**Issue by mfortini** [teamdigitale/padigitale2026-opendata#5]
Nella riga 22 c'è un uso errato delle virgolette che non permette la corretta interpretazione del file:

`"1.4.5 "Piattaforma Notifiche Digitali” Comuni (Settembre 2022)","1`...

**Comment by denismarini** [comment]
Grazie @mfortini, @sebbalex  andrebbe fatto un escape alla sorgente sul titolo, si deve parlare con Accenture o Sogei?

**Comment by mfortini** [comment]
Forse viene superato se si separano in due colonne misura e titolo. In alcuni casi ora il separatore è lo spazio e in altri il trattino

**Comment by radema** [comment]
Il nome dell'avviso è definito a mano da chi crea l'avviso. Lo tratterei in fase di export dati con un'operazione di formattazione stringhe.

**Comment by radema** [comment]
Chiudo l'issue perché dovrebbe essere stata definitivamente risolta con il rilascio di oggi.
